sayyoralar = ["Venera", "Neptun", "Mars", "Quyosh", "Uranium"]
print(sayyoralar)
print(sayyoralar[0:3])
sonlar = list(range(0,11))
print(sonlar)
print(max(sonlar))
print(min(sonlar))
print(sum(sonlar))
sayyoralar.sort()
print(sayyoralar)
sayyoralar.sort(reverse= True)
print(sayyoralar)
sayyoralar.reverse()
print(sayyoralar)
print(sorted(sonlar))
print(len(sayyoralar))
kiyimlar=("Tufli", "Rubashka", "Ko'ylak", "Shim")
print(kiyimlar)
kiyimlar = list(kiyimlar)
kiyimlar[0] = "Jiletka"
print(kiyimlar)
kiyimlar = tuple(kiyimlar)
print(kiyimlar[-1])
print(kiyimlar)
kiyimlar[2] = "Pomidor"
